# Enable AndroidX (REQUIRED for modern Android & Jetpack Compose)
android.useAndroidX=true
android.enableJetifier=true

# Improve build performance (safe defaults)
# Improve build performance (safe defaults)
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.java.home=C:/Program Files/Android/Android Studio/jbr